packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  "esbuild": true
  "msgpackr-extract": true
  "workerd": true
  "prisma": true
  "@prisma/client": true
  "@prisma/engines": true
  "@nestjs/core": true
  "@nestjs/cli": true
  youtube-dl-exec: set this to true or false
  '@sentry/cli': set this to true or false
  '@sentry/node-cpu-profiler': set this to true or false
