packages:
  - "apps/*"
  - "packages/*"

allowBuilds:
  "esbuild": true
  "msgpackr-extract": true
  "workerd": true
  "prisma": true
  "@prisma/client": true
  "@prisma/engines": true
  "@nestjs/core": true
  "@nestjs/cli": true
  youtube-dl-exec: true
  '@sentry/cli': true
  '@sentry/node-cpu-profiler': true
